# Generated by Django 5.2.6 on 2025-12-11 15:18

import contextlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_product_orderitem_product_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='note',
            field=models.TextField(default=contextlib.nullcontext),
        ),
    ]
