# Generated by Django 5.2.6 on 2025-12-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_rating',
            field=models.BooleanField(default=False),
        ),
    ]
