# Generated by Django 5.2.6 on 2025-12-25 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_is_rating'),
        ('voucher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voucher.uservoucher'),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='voucher.voucher'),
        ),
    ]
