# Generated by Django 5.2.6 on 2025-12-15 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_products_pr_categor_9edb3d_idx_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
