# Generated by Django 5.2.6 on 2025-12-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='district',
            field=models.CharField(default='', max_length=255),
        ),
    ]
