# Generated by Django 5.2.6 on 2025-12-15 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0004_delete_review'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0)),
                ('comment', models.TextField(blank=True)),
                ('review_date', models.DateTimeField(auto_now_add=True)),
                ('is_browse', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_account', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_product', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['product'], name='reviews_rev_product_a9ee0d_idx'), models.Index(fields=['account'], name='reviews_rev_account_a0bebb_idx'), models.Index(fields=['product', '-review_date'], name='reviews_rev_product_087041_idx')],
            },
        ),
    ]
