# Generated by Django 5.2.6 on 2025-12-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='is_browse',
        ),
        migrations.AddField(
            model_name='review',
            name='status',
            field=models.TextField(default='Pending'),
        ),
    ]
